name: Build & Deploy to GKE with Helm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mcp-server-kafka
      REGISTRY: gcr.io   # Change to your Artifact Registry region OR gcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Authenticate to GCP
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      # Configure Docker to push to Artifact Registry / GCR
      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker $REGISTRY --quiet

      # Build & push the image
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=$REGISTRY/${{ secrets.GCP_PROJECT }}/$IMAGE_NAME:${GITHUB_SHA::7}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Get GKE credentials
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      # Deploy Helm chart with new image tag
      - name: Deploy with Helm
        run: |
          helm upgrade --install mcp-server-kafka ./charts/mcp-server-kafka \
            --namespace mcp-server \
            --create-namespace \
            --set image.repository=$REGISTRY/${{ secrets.GCP_PROJECT }}/$IMAGE_NAME \
            --set image.tag=${GITHUB_SHA::7}
